### PR TITLE
[FEAT] Add maxStartAttemptCount option

### PR DESCRIPTION
**Pull request by samuel-olivier**

### CODE REVIEW

**Review by CGNonofr — CHANGES_REQUESTED** [review]
How will you pass the option?

What about putting it inside `LanguageClientOptions`?

**Comment by samuel-olivier** [comment]
@CGNonofr amended + wrapped the loop + I added the export of the type in the index: [feat: add maxStartAttemptCount option](https://github.com/CodinGame/monaco-languageclient-wrapper/pull/42/commits/826cda7da22a1db9b76c95e362bbb0bb72961a2a)

**Comment by CGNonofr** [comment]
> @CGNonofr amended + wrapped the loop + I added the export of the type in the index: [feat: add maxStartAttemptCount option](https://github.com/CodinGame/monaco-languageclient-wrapper/pull/42/commits/826cda7da22a1db9b76c95e362bbb0bb72961a2a)

I still don't understand how you'll provide this options, the LanguageClientManager class constructor is not exported by this lib

**Comment by samuel-olivier** [comment]
> > @CGNonofr amended + wrapped the loop + I added the export of the type in the index: [feat: add maxStartAttemptCount option](https://github.com/CodinGame/monaco-languageclient-wrapper/pull/42/commits/826cda7da22a1db9b76c95e362bbb0bb72961a2a)
> 
> I still don't understand how you'll provide this options, the LanguageClientManager class constructor is not exported by this lib

Well actually it's exported in the index but indeed I also need to add the options to the createLanguageClientManager function: [fix: add options to createLanguageClientManager](https://github.com/CodinGame/monaco-languageclient-wrapper/pull/42/commits/01abf3cdd8ca3f053e7529dfd4d9443d43273864)

**Review by CGNonofr — APPROVED** [review]

**Pull request merged**
